# dinov2/configs/train/custom_vit_small.yaml
# Inherit from the base config
# dino:
#   head_n_prototypes: 131072
#   head_bottleneck_dim: 384
# ibot:
#   separate_head: true
  # head_n_prototypes: 131072
train:
  batch_size_per_gpu: 16
  dataset_path: CustomSatellite:split=TRAIN:root=/work/lamlab/data/PW-l/
  centering: "sinkhorn_knopp"
student:
  arch: vit_large
  patch_size: 8
  # drop_path_rate: 0.4
  # ffn_layer: mlp
  block_chunks: 4
# teacher:
#   momentum_teacher: 0.994
optim:
  epochs: 200
#   weight_decay_end: 0.2
#   base_lr: 2.0e-04  # learning rate for a batch size of 1024
  warmup_epochs: 20
#   layerwise_decay: 1.0
# crops:
#   local_crops_size: 98